/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Runs */
        get: operations["list_runs_v1_runs_get"];
        put?: never;
        /** Start Run */
        post: operations["start_run_v1_runs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/runs/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Status */
        get: operations["get_status_v1_runs__run_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/runs/{run_id}/export.md": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Export Md */
        get: operations["export_md_v1_runs__run_id__export_md_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/runs/{run_id}/report": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Report */
        get: operations["get_report_v1_runs__run_id__report_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Battlecard */
        Battlecard: {
            /** Competitor */
            competitor: string;
            /** Landmines */
            landmines?: components["schemas"]["Landmine"][];
            /** Objections */
            objections?: components["schemas"]["Objection"][];
            /**
             * Overview
             * @description One sentence: who they are and who they sell to
             * @default
             */
            overview: string;
            pricing_comparison?: components["schemas"]["Claim"] | null;
            /** Proof Quotes */
            proof_quotes?: components["schemas"]["Quote"][];
            /**
             * Quick Dismiss
             * @description Talk track, max 50 words: acknowledge their strength, name the limit, pivot to our value
             * @default
             */
            quick_dismiss: string;
            /**
             * Tldr
             * @description Two short sentences: when we win, when we usually lose
             */
            tldr: string;
            /** Where We Lose */
            where_we_lose?: components["schemas"]["Threat"][];
            /** Where We Win */
            where_we_win?: components["schemas"]["Point"][];
        };
        /** CapRow */
        CapRow: {
            /** Name */
            name: string;
            them: components["schemas"]["CellView"];
            us: components["schemas"]["CellView"];
            /**
             * Verdict
             * @enum {string}
             */
            verdict: "lead" | "even" | "behind" | "unknown";
        };
        /** Capability */
        Capability: {
            /** Cells */
            cells?: components["schemas"]["Cell"][];
            /**
             * Name
             * @description Buyer-facing capability, max 5 words
             */
            name: string;
        };
        /** CapabilityMatrix */
        CapabilityMatrix: {
            /** Capabilities */
            capabilities?: components["schemas"]["Capability"][];
        };
        /** CapabilityView */
        CapabilityView: {
            /** Cells */
            cells: components["schemas"]["CellView"][];
            /** Name */
            name: string;
        };
        /** CardView */
        CardView: {
            /** Axis Lo */
            axis_lo: number;
            evidence: components["schemas"]["Evidence"];
            /** Known */
            known: number;
            /** Ratings */
            ratings: components["schemas"]["RatingPair"][];
            /** Rows */
            rows: components["schemas"]["CapRow"][];
            tally: components["schemas"]["Tally"];
        };
        /** Cell */
        Cell: {
            /** Company */
            company: string;
            /**
             * Note
             * @description Max 8 words, e.g. 'Add-on, extra cost'
             * @default
             */
            note: string;
            /** Sources */
            sources?: string[];
            /**
             * Status
             * @default unknown
             * @enum {string}
             */
            status: "full" | "partial" | "none" | "unknown";
        };
        /** CellView */
        CellView: {
            /**
             * Company
             * @default
             */
            company: string;
            /**
             * Note
             * @default
             */
            note: string;
            /**
             * Self
             * @default false
             */
            self: boolean;
            /** Sources */
            sources?: string[];
            /**
             * Status
             * @default unknown
             * @enum {string}
             */
            status: "full" | "partial" | "none" | "unknown";
        };
        /** Change */
        Change: {
            /** Change */
            change: string;
            /** Company */
            company: string;
            /**
             * Severity
             * @enum {string}
             */
            severity: "high" | "medium" | "low";
            /** Sources */
            sources?: string[];
            /** Why It Matters */
            why_it_matters: string;
        };
        /** ChangeReport */
        ChangeReport: {
            /** Changes */
            changes?: components["schemas"]["Change"][];
        };
        /** Claim */
        Claim: {
            /** Sources */
            sources?: string[];
            /** Text */
            text: string;
        };
        /** CompanyFacts */
        CompanyFacts: {
            /** Employees */
            employees?: string | null;
            /** Founded */
            founded?: string | null;
            /** Headquarters */
            headquarters?: string | null;
            /** Owner */
            owner?: string | null;
            /** Wikipedia */
            wikipedia?: string | null;
        };
        /** CompanyIn */
        CompanyIn: {
            /** Domain */
            domain?: string | null;
            /** Name */
            name: string;
        };
        /** CompanyProfile */
        CompanyProfile: {
            /** Domain */
            domain?: string | null;
            /** Hiring Signals */
            hiring_signals?: components["schemas"]["Claim"][];
            /** Key Capabilities */
            key_capabilities?: components["schemas"]["Claim"][];
            /**
             * Name
             * @default
             */
            name: string;
            /** @description How the company describes itself, in one line */
            positioning?: components["schemas"]["Claim"] | null;
            pricing_summary?: components["schemas"]["Claim"] | null;
            /** Pricing Tiers */
            pricing_tiers?: components["schemas"]["PriceTier"][];
            /** Quotes */
            quotes?: components["schemas"]["Quote"][];
            /** Ratings */
            ratings?: components["schemas"]["Rating"][];
            /** Recent Changes */
            recent_changes?: components["schemas"]["Claim"][];
            /** Review Strengths */
            review_strengths?: components["schemas"]["Claim"][];
            /** Review Weaknesses */
            review_weaknesses?: components["schemas"]["Claim"][];
            /** Target Customers */
            target_customers?: components["schemas"]["Claim"][];
        };
        /** CreateRunOut */
        CreateRunOut: {
            /** Reused */
            reused: boolean;
            /** Run Id */
            run_id: string;
            /**
             * Status
             * @enum {string}
             */
            status: "queued" | "running" | "succeeded" | "partial" | "failed";
        };
        /** Evidence */
        Evidence: {
            /** Independent */
            independent: number;
            /** Pct */
            pct: number;
            /** Total */
            total: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** Landmine */
        Landmine: {
            /**
             * Question
             * @description A question our rep asks that exposes a competitor weakness
             */
            question: string;
            /** Sources */
            sources?: string[];
            /** Why */
            why: string;
        };
        /** MarketRating */
        MarketRating: {
            /** By Site */
            by_site: {
                [key: string]: components["schemas"]["Rating"];
            };
            /** Name */
            name: string;
        };
        /** Objection */
        Objection: {
            /**
             * Objection
             * @description What a prospect says in favour of the competitor
             */
            objection: string;
            /** Response */
            response: string;
            /** Sources */
            sources?: string[];
        };
        /** Point */
        Point: {
            /**
             * Detail
             * @description One supporting sentence, max 25 words
             * @default
             */
            detail: string;
            /**
             * Headline
             * @description Scannable takeaway, max 10 words
             */
            headline: string;
            /** Sources */
            sources?: string[];
        };
        /** PositioningAnalysis */
        PositioningAnalysis: {
            /** @description A positioning angle our company could credibly own */
            recommended_angle?: components["schemas"]["Claim"] | null;
            /**
             * Table Stakes
             * @description Themes most players claim - not differentiating
             */
            table_stakes?: components["schemas"]["SharedClaim"][];
            /**
             * White Space
             * @description Buyer needs (from reviews) nobody clearly owns
             */
            white_space?: components["schemas"]["WhiteSpace"][];
        };
        /** PriceTier */
        PriceTier: {
            /** Name */
            name: string;
            /**
             * Notable
             * @default
             */
            notable: string;
            /**
             * Price
             * @description As stated, e.g. '$49/agent/month billed annually' or 'Contact sales'
             */
            price: string;
            /** Sources */
            sources?: string[];
        };
        /** ProgressItem */
        ProgressItem: {
            /** At */
            at: string;
            /**
             * Note
             * @default
             */
            note: string;
            /** Stage */
            stage: string;
            /**
             * Status
             * @enum {string}
             */
            status: "running" | "done" | "skipped" | "retrying" | "failed";
        };
        /** Quote */
        Quote: {
            /**
             * Quote
             * @description Verbatim text copied exactly from the source
             */
            quote: string;
            /**
             * Sentiment
             * @enum {string}
             */
            sentiment: "praise" | "pain" | "switching";
            /** Source */
            source: string;
        };
        /** Rating */
        Rating: {
            /**
             * Out Of
             * @default 5
             */
            out_of: number;
            /**
             * Rating
             * @description Average star rating exactly as shown in the source
             */
            rating: number;
            /**
             * Review Count
             * @description Number of reviews, only if stated
             */
            review_count?: number | null;
            /**
             * Site
             * @description Review site, e.g. 'G2', 'Capterra'
             */
            site: string;
            /** Source */
            source: string;
        };
        /** RatingPair */
        RatingPair: {
            /** Site */
            site: string;
            them?: components["schemas"]["Rating"] | null;
            us?: components["schemas"]["Rating"] | null;
        };
        /** ReportOut */
        ReportOut: {
            /** Battlecards */
            battlecards: components["schemas"]["Battlecard"][];
            /**
             * Category
             * @default
             */
            category: string;
            changes?: components["schemas"]["ChangeReport"] | null;
            /** Company */
            company: string;
            /** Competitors */
            competitors: string[];
            /**
             * Degraded
             * @default false
             */
            degraded: boolean;
            /** Facts */
            facts?: {
                [key: string]: components["schemas"]["CompanyFacts"];
            };
            /**
             * Featured
             * @default false
             */
            featured: boolean;
            /** Id */
            id: string;
            matrix?: components["schemas"]["CapabilityMatrix"] | null;
            /**
             * Model
             * @default
             */
            model: string;
            /** Notes */
            notes?: {
                [key: string]: string;
            };
            positioning?: components["schemas"]["PositioningAnalysis"] | null;
            /** Previous Run */
            previous_run?: string | null;
            /** Profiles */
            profiles: {
                [key: string]: components["schemas"]["CompanyProfile"];
            };
            /** Run Date */
            run_date: string;
            /**
             * Search Provider
             * @default
             */
            search_provider: string;
            /** Sources */
            sources: components["schemas"]["SourceOut"][];
            /** Stats */
            stats?: {
                [key: string]: number;
            };
            /**
             * Status
             * @enum {string}
             */
            status: "queued" | "running" | "succeeded" | "partial" | "failed";
            /** Usage */
            usage?: {
                [key: string]: number;
            };
            views: components["schemas"]["Views"];
        };
        /** RunRequest */
        RunRequest: {
            /**
             * Category
             * @default
             */
            category: string;
            company: components["schemas"]["CompanyIn"];
            /** Competitors */
            competitors: components["schemas"]["CompanyIn"][];
        };
        /** RunStatusOut */
        RunStatusOut: {
            /** Company */
            company: string;
            /** Competitors */
            competitors: string[];
            /** Created At */
            created_at: string;
            /** Current Stage */
            current_stage?: string | null;
            /**
             * Degraded
             * @default false
             */
            degraded: boolean;
            /** Error */
            error?: string | null;
            /** Id */
            id: string;
            /** Progress */
            progress: components["schemas"]["ProgressItem"][];
            /**
             * Status
             * @enum {string}
             */
            status: "queued" | "running" | "succeeded" | "partial" | "failed";
        };
        /** RunSummary */
        RunSummary: {
            /**
             * Category
             * @default
             */
            category: string;
            /** Company */
            company: string;
            /** Competitors */
            competitors: string[];
            /** Created At */
            created_at: string;
            /**
             * Featured
             * @default false
             */
            featured: boolean;
            /** Id */
            id: string;
            /** Run Date */
            run_date: string;
            /**
             * Status
             * @enum {string}
             */
            status: "queued" | "running" | "succeeded" | "partial" | "failed";
        };
        /** SharedClaim */
        SharedClaim: {
            /** Companies */
            companies: string[];
            /** Sources */
            sources?: string[];
            /** Theme */
            theme: string;
        };
        /** SourceOut */
        SourceOut: {
            /** Category */
            category: string;
            /** Company */
            company: string;
            /** Id */
            id: string;
            /**
             * Origin
             * @default independent
             */
            origin: string;
            /** Published */
            published?: string | null;
            /**
             * Title
             * @default
             */
            title: string;
            /** Url */
            url: string;
        };
        /** Tally */
        Tally: {
            /** Behind */
            behind: number;
            /** Even */
            even: number;
            /** Lead */
            lead: number;
            /** Unknown */
            unknown: number;
        };
        /** Threat */
        Threat: {
            /**
             * Counter
             * @description How a rep neutralises this, max 20 words
             * @default
             */
            counter: string;
            /**
             * Detail
             * @description One supporting sentence, max 25 words
             * @default
             */
            detail: string;
            /**
             * Headline
             * @description Scannable takeaway, max 10 words
             */
            headline: string;
            /** Sources */
            sources?: string[];
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** Views */
        Views: {
            /** Cards */
            cards: components["schemas"]["CardView"][];
            /** Market Ratings */
            market_ratings: components["schemas"]["MarketRating"][];
            /** Matrix */
            matrix: components["schemas"]["CapabilityView"][];
            /** Names */
            names: string[];
            /** Sites */
            sites: string[];
        };
        /** WhiteSpace */
        WhiteSpace: {
            /** Evidence */
            evidence: string;
            /** Opportunity */
            opportunity: string;
            /** Sources */
            sources?: string[];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    list_runs_v1_runs_get: {
        parameters: {
            query?: {
                featured?: boolean;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunSummary"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    start_run_v1_runs_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RunRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateRunOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_status_v1_runs__run_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunStatusOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    export_md_v1_runs__run_id__export_md_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_report_v1_runs__run_id__report_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReportOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
